# Generated by Django 6.0.1 on 2026-01-27 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract1', models.FileField(blank=True, null=True, upload_to='abstracts/')),
                ('abstract2', models.FileField(blank=True, null=True, upload_to='abstracts/')),
                ('abstract3', models.FileField(blank=True, null=True, upload_to='abstracts/')),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_submission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
