# Generated by Django 6.0.1 on 2026-01-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('MCA', 'MCA'), ('IMCA', 'IMCA')], max_length=10, null=True),
        ),
    ]
