# Generated by Django 6.0.1 on 2026-01-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='project_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='similarity_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION', 'Revision Required')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='batch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
