# Generated by Django 6.0.1 on 2026-01-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_projectsubmission_project_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='approved_abstract',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
